name: PipelineRPA

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f Requirements-RPA.txt ]; then pip install -r Requirements-RPA.txt; fi

    - name: Deploy no EC2 - AWS
      run: |
        echo "Conectando no EC2"
        echo "${{secrets.Chave_RPA}}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i private_key "${{secrets.HOST}}" << EOF
          cd "analise_de_dados/RPA Git/"
          git pull
        EOF
